Repository hashicorp/terraform-plugin-go, pull requests merged in 2021-04, with the labels that each got.

#71 Add support for plugin protocol v6
  tfprotov6/data_source.go
  tfprotov6/diagnostic.go
  tfprotov6/doc.go
  tfprotov6/dynamic_value.go
  tfprotov6/dynamic_value_json.go
  tfprotov6/dynamic_value_json_test.go
  tfprotov6/dynamic_value_msgpack.go
  tfprotov6/dynamic_value_msgpack_test.go
  tfprotov6/internal/fromproto/attribute_path.go
  tfprotov6/internal/fromproto/data_source.go
  tfprotov6/internal/fromproto/diagnostic.go
  tfprotov6/internal/fromproto/provider.go
  tfprotov6/internal/fromproto/resource.go
  tfprotov6/internal/fromproto/schema.go
  tfprotov6/internal/fromproto/state.go
  tfprotov6/internal/fromproto/string_kind.go
  tfprotov6/internal/fromproto/types.go
  tfprotov6/internal/tfplugin6/generate.sh
  tfprotov6/internal/tfplugin6/tfplugin6.pb.go
  tfprotov6/internal/tfplugin6/tfplugin6.proto
  tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go
  tfprotov6/internal/toproto/attribute_path.go
  tfprotov6/internal/toproto/data_source.go
  tfprotov6/internal/toproto/diagnostic.go
  tfprotov6/internal/toproto/dynamic_value.go
  tfprotov6/internal/toproto/provider.go
  tfprotov6/internal/toproto/resource.go
  tfprotov6/internal/toproto/schema.go
  tfprotov6/internal/toproto/state.go
  tfprotov6/internal/toproto/string_kind.go
  tfprotov6/provider.go
  tfprotov6/resource.go
  tfprotov6/schema.go
  tfprotov6/server/doc.go
  tfprotov6/server/plugin.go
  tfprotov6/server/server.go
  tfprotov6/state.go
  tfprotov6/string_kind.go
Labels: enhancement

#74 Implement OptionalAttributes for Objects.
  .changelog/74.txt
  tfprotov5/dynamic_value_msgpack.go
  tfprotov6/dynamic_value_msgpack.go
  tftypes/list.go
  tftypes/list_test.go
  tftypes/map.go
  tftypes/map_test.go
  tftypes/object.go
  tftypes/object_test.go
  tftypes/primitive.go
  tftypes/primitive_test.go
  tftypes/set.go
  tftypes/set_test.go
  tftypes/tuple.go
  tftypes/tuple_test.go
  tftypes/type.go
  tftypes/type_json_test.go
  tftypes/value.go
  tftypes/value_object_test.go
Labels: enhancement

#77 Refactor JSON and MsgPack parsing code.
  tfprotov5/dynamic_value.go
  tfprotov5/dynamic_value_json.go
  tfprotov5/dynamic_value_json_test.go
  tfprotov5/dynamic_value_msgpack.go
  tfprotov5/dynamic_value_msgpack_test.go
  tfprotov5/state.go
  tfprotov6/dynamic_value.go
  tfprotov6/dynamic_value_json.go
  tfprotov6/dynamic_value_json_test.go
  tfprotov6/dynamic_value_msgpack.go
  tfprotov6/dynamic_value_msgpack_test.go
  tfprotov6/state.go
  tftypes/value_json.go
  tftypes/value_json_test.go
  tftypes/value_msgpack.go
  tftypes/value_msgpack_test.go
Labels: compatibility

#78 Fix AttributePaths when parsing JSON/MsgPack.
  tftypes/value_json.go
  tftypes/value_msgpack.go
Labels: bug

#79 Fix NewValue checks to be properly recursive
  tftypes/list.go
  tftypes/map.go
  tftypes/object.go
  tftypes/set.go
  tftypes/tuple.go
  tftypes/type.go
  tftypes/value_list_test.go
  tftypes/value_map_test.go
  tftypes/value_object_test.go
  tftypes/value_set_test.go
  tftypes/value_test.go
  tftypes/value_tuple_test.go
Labels: bug
