Repository hashicorp/terraform-plugin-go, pull requests merged in 2022-02, with the labels that each got.

#149 tftypes: Further document Object type OptionalAttributes field usage
  tftypes/object.go
Labels: documentation

#150 Propagate provider name into GRPCProviderPlugin
  tfprotov5/tf5server/server.go
Labels: bug

#153 tfprotov5/tf5server: Ensure server options are passed through on startup
  .changelog/153.txt
  tfprotov5/tf5server/server.go
Labels: bug

#158 tfprotov5+tfprotov6: Introduce ValueType() methods for Schema types
  .changelog/158.txt
  tfprotov5/schema.go
  tfprotov5/schema_test.go
  tfprotov6/schema.go
  tfprotov6/schema_test.go
Labels: enhancement
