Repository hashicorp/terraform-plugin-go, pull requests merged in 2024-02, with the labels that each got.

#380 tfprotov5+tfprotov6: Replace usage of diagnostics in CallFunction RPC with function error
  .changes/unreleased/BREAKING CHANGES-20240221-103010.yaml
  .changes/unreleased/NOTES-20240222-080818.yaml
  internal/logging/keys.go
  tfprotov5/diagnostic.go
  tfprotov5/function.go
  tfprotov5/function_error.go
  tfprotov5/internal/diag/diagnostics.go
  tfprotov5/internal/funcerr/doc.go
  tfprotov5/internal/funcerr/function_error.go
  tfprotov5/internal/funcerr/function_error_test.go
  tfprotov5/internal/funcerr/pointer_test.go
  tfprotov5/internal/tf5serverlogging/downstream_request.go
  tfprotov5/internal/tf5serverlogging/downstream_request_test.go
  tfprotov5/internal/tf5serverlogging/pointer_test.go
  tfprotov5/internal/tfplugin5/tfplugin5.pb.go
  tfprotov5/internal/tfplugin5/tfplugin5.proto
  tfprotov5/internal/toproto/diagnostic.go
  tfprotov5/internal/toproto/diagnostic_test.go
  tfprotov5/internal/toproto/function.go
  tfprotov5/internal/toproto/function_error.go
  tfprotov5/internal/toproto/function_test.go
  tfprotov5/tf5server/server.go
  tfprotov6/diagnostic.go
  tfprotov6/function.go
  tfprotov6/function_error.go
  tfprotov6/internal/diag/diagnostics.go
  tfprotov6/internal/funcerr/doc.go
  tfprotov6/internal/funcerr/function_error.go
  tfprotov6/internal/funcerr/function_error_test.go
  tfprotov6/internal/funcerr/pointer_test.go
  tfprotov6/internal/tf6serverlogging/downstream_request.go
  tfprotov6/internal/tf6serverlogging/downstream_request_test.go
  tfprotov6/internal/tf6serverlogging/pointer_test.go
  tfprotov6/internal/tfplugin6/tfplugin6.pb.go
  tfprotov6/internal/tfplugin6/tfplugin6.proto
  tfprotov6/internal/toproto/diagnostic.go
  tfprotov6/internal/toproto/diagnostic_test.go
  tfprotov6/internal/toproto/function.go
  tfprotov6/internal/toproto/function_error.go
  tfprotov6/internal/toproto/function_test.go
  tfprotov6/tf6server/server.go
Labels: breaking-change

#381 all: Update Go Module to Go 1.21
  .changes/unreleased/NOTES-20240221-121520.yaml
  .github/workflows/ci-go.yml
  README.md
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: dependencies

#383 tftypes: Adjust `(tftypes.Value).Equal` function to support dynamic value comparisons
  .changes/unreleased/BUG FIXES-20240228-171104.yaml
  tftypes/value.go
  tftypes/value_test.go
Labels: bug
